server:
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: ROOT
  jpa:
    show-sql: true # mostrar en log las querys que se hacen
    hibernate:
      ddl-auto: update #validar si corresponden las entidades con las tablas y actualizar 
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy # dialecto para la consulta
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect  # dialecto para la consulta